<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LINK_LOGIN</name>
   <tag></tag>
   <elementGuidId>3bb1b4b5-6ace-4b2f-9cd3-2f30c4aa2e60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;myform&quot;]/div[7]/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;myform&quot;]/div[7]/p/a</value>
   </webElementProperties>
</WebElementEntity>
