<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LINK_FORGET_PASSWORD</name>
   <tag></tag>
   <elementGuidId>8f8e96a2-d87e-4433-95a5-7b5e0cd9d5c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;myform&quot;]/div[3]/p[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;myform&quot;]/div[3]/p[1]/a</value>
   </webElementProperties>
</WebElementEntity>
