<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LINK_SIGNUP</name>
   <tag></tag>
   <elementGuidId>9b1037f2-ddfc-445d-a54d-e83eb33fe109</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;myform&quot;]/div[3]/p[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;myform&quot;]/div[3]/p[2]/a</value>
   </webElementProperties>
</WebElementEntity>
